<?php

namespace Jazzyweb\MapBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CentrosMarkerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentroMarkerRepository extends EntityRepository
{
    public function findPorProvincia($provincia)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM JwMapBundle:CentroMarker c WHERE c.provincia LIKE :provincia'
            )
            ->setParameter('provincia', '%'.$provincia.'%')
            ->getResult();
    }

    public function findPorAutonomia($autonomia)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM JwMapBundle:CentroMarker c WHERE c.autonomia LIKE :autonomia'
            )
            ->setParameter('autonomia', '%'.$autonomia.'%')
            ->getResult();
    }

    public function findPorLocalidad($localidad)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM JwMapBundle:CentroMarker c WHERE c.localidad LIKE :localidad'
            )
            ->setParameter('localidad', '%'.$localidad.'%')
            ->getResult();
    }

    public function findPorProvinciaYTipo($provincia, $tipo)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM JwMapBundle:CentroMarker c WHERE c.provincia LIKE :provincia and c.tipologiaMod18may = :tipo'
            )
            ->setParameters(array('provincia' => '%'.$provincia.'%', 'tipo' => $tipo))
            ->getResult();
    }

    public function findPorAutonomiaYTipo($autonomia, $tipo)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM JwMapBundle:CentroMarker c WHERE c.autonomia LIKE :autonomia'
            )
            ->setParameters(array('autonomia' => '%'.$autonomia.'%', 'tipo' => $tipo))
            ->getResult();
    }

    public function findPorLocalidadYTipo($localidad, $tipo)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM JwMapBundle:CentroMarker c WHERE c.localidad LIKE :localidad'
            )
            ->setParameters(array('provincia' => '%'.$localidad.'%', 'tipo' => $tipo))
            ->getResult();
    }

    protected function getTipo($tipo){

        $tipos = array('TIPO 1', 'TIPO 2', 'TIPO 3');


    }
}
